# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=collide2v_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/mean_auc"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///logs/optuna_logs/optuna.db

    # name of the study to persist optimization results
    study_name: 18class_optimization_fullsweep_200trials

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 10

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      n_startup_trials: 30 # number of random sampling runs before optimization starts
      multivariate: true
      n_ei_candidates: 48
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      warn_independent_sampling: false

    # define hyperparameter search space
    params:
      model.optimizer.lr: tag(log, interval(3e-5, 1e-3))
      model.optimizer.weight_decay: tag(log, interval(1e-5, 1e-1))
      model.optimizer.betas: choice([0.9, 0.999], [0.9, 0.99], [0.95, 0.999], [0.95, 0.99])
      model.optimizer.eps: choice(1e-09, 1e-08, 1e-07)
      trainer.gradient_clip_val: choice(0.0, 1.0, 5.0, 10.0)
      model.d_model: choice(
        64,
        256,
        512
        )
      model.num_layers: choice(
        2,
        4,
        6
        )
      model.d_ff: choice(
        256,
        512,
        1024,
        2048
        )
      model.dropout: tag(lin, interval(0.0, 0.3))
      model.n_heads: choice(
        4,
        8,
        16
        )
