_target_: src.models.collide2v_tinytransformer.COLLIDE2VTransformerLitModule

d_model: 512
n_heads: 8
num_layers: 4
d_ff: 256
dropout: 0
compile: false

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2e-4
  weight_decay: 1e-2
  eps: 1e-08
  betas: [0.9, 0.999]

scheduler: null

#scheduler:
#  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
#  _partial_: true
  #T_max: ${trainer.max_epochs}
